### ISSUE TITLE
Create Shiny dashboard

### ISSUE THREAD

**Issue by athowes** [athowes/multi-agyw#37]
* Too many plots to reasonably put in a paper
* Suggest to create Shiny dashboard to display

**Comment by athowes** [comment]
Can use the following for code / structure / aesthetic inspiration:
* https://github.com/mrc-ide/shinyrob
* https://github.com/mrc-ide/shiny90

**Comment by jeffeaton** [comment]
Be cautious about using Shiny90 as an example. That uses a lot of non-standard conventions.  Chat with with Rich and Rob before drawing on anything from there as an example.

Thanks,
Jeff

From: Adam Howes ***@***.***>
Date: Tuesday, 5 October 2021 at 09:52
To: athowes/multi-agyw ***@***.***>
Cc: Subscribed ***@***.***>
Subject: Re: [athowes/multi-agyw] Create Shiny dashboard (#37)

Can use the following for code / structure / aesthetic inspiration:

  *   https://github.com/mrc-ide/shinyrob
  *   https://github.com/mrc-ide/shiny90

**Comment by athowes** [comment]
Copied basic structure from [mrc-ide/shinyrob](https://github.com/mrc-ide/shinyrob) to [athowes/shiny-multi-agyw](https://github.com/athowes/shiny-multi-agyw). Closing this issue and continuing any development there.
