### ISSUE TITLE
TikZ flowchart of categories

### ISSUE THREAD

**Issue by athowes** [athowes/multi-agyw#54]

**Comment by kklot** [comment]
I used this before, needed a lot trial & error to get something nice, [draw.io](draw.io) is my goto for speed :)

**Comment by athowes** [comment]
Haha I definitely agree @kklot, but 'm a stubborn maths department member so I feel compelled. Here's a first version:

![image](https://user-images.githubusercontent.com/29818116/147835339-aaabe230-f449-4b4b-bcc1-07f282946b69.png)

**Comment by athowes** [comment]
This isn't 100% right but I can fix it going over the manuscript. Doesn't need to be here.
